# Generated by Django 4.2.3 on 2023-11-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=30, verbose_name="Area")),
                ("baja", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=30, verbose_name="Apellido")),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                ("mensaje", models.CharField(max_length=500, verbose_name="Mensaje")),
            ],
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=30, verbose_name="Apellido")),
                ("dni", models.IntegerField(verbose_name="DNI")),
                ("email", models.EmailField(max_length=50, verbose_name="Email")),
                ("legajo", models.CharField(max_length=30, verbose_name="Legajo")),
                ("matricula", models.IntegerField(verbose_name="Matricula")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Farmacia.area"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=30, verbose_name="Apellido")),
                ("email", models.EmailField(max_length=50, verbose_name="Email")),
                ("hitoria", models.IntegerField(verbose_name="H_clinica")),
            ],
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha del turno")),
                ("hora", models.TimeField(verbose_name="Hora del turno")),


                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Farmacia.medico",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Farmacia.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_receta", models.IntegerField(verbose_name="Nro_receta")),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Farmacia.paciente",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paciente",
            name="medico",
            field=models.ManyToManyField(
                through="Farmacia.Turno", to="Farmacia.medico"
            ),
        ),
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lote", models.CharField(max_length=30, verbose_name="Lote")),
                (
                    "laboratorio",
                    models.CharField(max_length=30, verbose_name="Laboratorio"),
                ),
                ("orden", models.IntegerField(verbose_name="Orden")),
                ("nombre", models.CharField(max_length=30, verbose_name="Nombre")),
                ("precio", models.IntegerField(verbose_name="Precio")),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Farmacia.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Farmaceutico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=30, verbose_name="Apellido")),
                ("dni", models.IntegerField(verbose_name="DNI")),
                ("email", models.EmailField(max_length=50, verbose_name="Email")),
                ("legajo", models.CharField(max_length=30, verbose_name="Legajo")),
                ("matricula", models.IntegerField(verbose_name="Matricula")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Farmacia.area"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
