# Generated by Django 4.2.3 on 2023-11-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Farmacia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turno",
            name="hora",
            field=models.TimeField(verbose_name="Hara"),
        ),
    ]
