# Generated by Django 4.2.3 on 2023-11-16 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Farmacia", "0002_area_medicamentos_medico_paciente_turno_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lote", models.CharField(max_length=30, verbose_name="Lote")),
                (
                    "laboratorio",
                    models.CharField(max_length=30, verbose_name="Laboratorio"),
                ),
                ("orden", models.IntegerField(verbose_name="Orden")),
                ("nombre", models.CharField(max_length=30, verbose_name="Nombre")),
                ("precio", models.IntegerField(verbose_name="Precio")),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Farmacia.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_receta", models.IntegerField(verbose_name="Nro_receta")),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Farmacia.paciente",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Medicamentos",
        ),
    ]
